// ── Changelog — the data behind the "What's new" panel ─────────────────────
// Newest release first. Versions & dates are grounded in the real git history
// (commit clusters by day), not invented. Each release carries a version, a
// date, and a localized title + bullet list. LATEST_VERSION drives the "new
// update" dot: when budget_changelog_seen differs from it, the menu shows a
// badge until the user opens this panel.

import type { Lang } from './i18n';

export interface Release {
  version: string;
  date: string; // ISO yyyy-mm-dd (real commit date)
  title: Record<Lang, string>;
  items: Record<Lang, string[]>;
}

export const CHANGELOG: Release[] = [
  {
    version: '1.12.0',
    date: '2026-09-18',
    title: { sv: 'Tanken bakom appen', en: 'The thinking behind the app', es: 'La idea detrás de la app' },
    items: {
      sv: [
        'Nytt: importera ditt kontoutdrag som CSV-fil från banken. Appen läser filen på din enhet — den skickas ingenstans — och gissar själv vilka kolumner som är datum, text och belopp. Stämmer gissningen inte rättar du den en gång, sedan minns appen uppställningen och frågar aldrig igen för samma bank',
        'Granskningen grupperar per ställe i stället för att räkna upp varje rad: sex ICA-köp blir ett beslut, inte sex. Poster du inte ger en kategori importeras inte',
        'Varje post hamnar i den månad dess eget datum tillhör, så en fil som spänner över två månader fyller båda — och appen säger vilka den rörde',
        'Ett kontoutdrag är oftast förra månadens, så månaden som ändras är sällan den du står på. Därför har sammanfattningen en knapp som tar dig dit',
        'Poster vars kategori den månadens budget saknar samlas under "Utanför budgeten" i stället för att inte synas alls. Importerar du till en månad du inte hunnit budgetera är pengarna kvar, syns och räknas med',
        'Nytt: appen sorterar kontoutdraget åt dig. Den kommer med en färdig svensk lista — ICA, Willys, SL, Västtrafiken, Telenor, Apoteket, Pressbyrån, Espresso House och några hundra till — så redan den första importen är till största delen ifylld',
        'Rättar du en kategori minns den det, och nästa gång väger din rättelse tyngre än listans gissning. Samma butik känns igen även när banken skriver ut ett annat kassanummer, och "Södermalmskyrkan" hittas trots att ordet sitter ihop',
        'Saknas en kategori som behövs föreslår appen att skapa den. Förslaget har streckad ram tills du trycker Importera — och kategorin skapas i den månad posterna hamnar i, inte den du råkar titta på',
        'Den gissar aldrig på en överföring, en uttagsavgift eller ett Swish till en privatperson. Där finns ingen butik att känna igen, och en felaktig kategori kostar mer än en tom',
        'Listan har en internationell del och en svensk. Netflix, Lidl, IKEA, Ryanair, Zalando, MediaMarkt och ett par hundra till känns igen oavsett land — den svenska halvan ligger ovanpå. Ett land läggs till när det finns en riktig fil att pröva den mot, aldrig ur minnet',
        'Importen läser fler europeiska filer: tyska datum som 31.08.26, belopp med valutan bredvid som "45,20 PLN", och exporter vars kolumnrubriker appen aldrig sett — då känns kolumnen igen på sitt innehåll i stället för på sitt namn',
        'Kontoutdragets kolumner går att ändra i efterhand. Lärde sig appen fel uppställning för en bank satt den fast för alltid — nu finns "Ändra kolumner" i granskningen, och den glömmer den sparade gissningen på köpet',
        'Ny knapp i Uppföljning: rensa hela månadens utfall på en gång. Vägen tillbaka från en import av fel fil, i stället för att ta bort hundra poster en i taget',
        '"Återställ månad" säger nu vad den gör. Den nollställer budgeten och rör inte det registrerade utfallet — tidigare stod det att den nollställde månaden, och posterna låg kvar utan ett ord',
        'Löneperioden styr nu Uppföljning. Lever du 25→24 hamnar hyran och alla fasta utgifter i rätt budgetmånad — på ett riktigt kontoutdrag låg 74,5 % av utgifterna i fel månad innan. Budgetens belopp rörs inte, och är perioden av fungerar allt precis som förut',
        'Importen läser nu TRANSAKTIONSDAGEN, inte bokföringsdagen. Banken bokför lönen kvällen innan så pengarna finns på lönedagen — på ett riktigt kontoutdrag var det den enda av 107 rader som hamnade i fel budgetmånad, och det var lönen: månadens största belopp, på fel sida om strecket',
        'Perioden flyttar sig själv över helger. Infaller den 25:e på en lördag kommer lönen på fredagen — fyra månader av tolv under 2026. Du behöver inte göra något; appen räknar från dagen pengarna faktiskt kom',
        'Och blir det ändå fel kan du nåla fast en enskild period för hand under Uppföljning. Gäller bara den månaden, övriga följer regeln',
        'Byter du startdag flyttas de registrerade posterna med, och appen räknar upp hur många innan den gör det. Ingenting försvinner — varje post bär sitt eget datum, så omflyttningen är exakt och går att göra om',
        'Nytt i Uppföljning: välj Månad, 3, 6 eller 12 månader. Plan och utfall summeras över spannet — och en månad utan budget räknas inte som noll, den sägs ut',
        'Över flera månader grupperas en kategori per ställe i stället för per datum. "Espresso House, 8 poster, 448 kr" i stället för åtta rader utspridda — vyn ett kontoutdrag aldrig ger dig, eftersom det sorterar på datum',
        'Grupperingen per ställe går nu att klicka: "Espresso House, 4 poster, 224 kr" fälls ut till sina datum, där du kan rätta eller ta bort en post. Och du kan välja Per datum i stället om du hellre läser i tidsordning',
        'Sorteraren läser nu beskrivningar som banken kapat. Kortrader klipps vid sexton tecken, så sista ordet blir ofta en stump — "Do Re Mi Restaur", "ANTIKA RESTAURAN", "2627705203 Nordn" känns igen ändå. Bara som sista utväg: en hel ordträff vinner alltid över en stump',
        'Importen kastar ingenting längre. Det appen inte kan placera hamnar i "Övrigt", och överföringar mellan dina egna konton i "Överföring" — tidigare försvann de bara, och på ett riktigt kontoutdrag var det 173 av 471 transaktioner du sedan inte kunde nå',
        'Överföringar räknas INTE som utgift. Att flytta 5 000 till ditt eget sparkonto är inte att spendera 5 000 — raden ligger under Totalt ut, utanför summan. På ett riktigt kontoutdrag hade den annars blåst upp en månads utgifter från 29 927 till 58 514 kr',
        'Och nu går det att flytta ett helt ställe till rätt kategori inifrån Uppföljning — hela gruppen på en gång, och valet lärs så nästa import hamnar rätt direkt',
        'Och behövs en kategori som inte finns skapar du den på stället — "+ Ny kategori…" i samma meny. Den läggs till i alla månader du har i vyn, så posterna du flyttar dit inte blir hemlösa i de andra',
        'Ny standardkategori: Lån & Krediter. Studielån, bolån, amortering och köp-nu-betala-sen passade ingen av de sju andra — CSN hamnade i Övrigt med ingenstans att ta vägen. Nu känns CSN, Kronofogden, SBAB, Klarna, Qliro och ett trettiotal till igen automatiskt',
        'Sorteraren har fått två listor till: en amerikansk och en spansk. Walmart, Kroger, Walgreens, Chevron, Mercadona, Renfe, Iberdrola, Movistar och ett par hundra andra. Den svenska listan är fortfarande den enda som är mätt mot ett riktigt kontoutdrag — de två nya är en rimlig första gissning, och det är efter din första rättelse den blir riktigt bra i alla länder',
        'Och tolken läser nu amerikanska filer rätt. Chase och Wells Fargo skriver 09/05/2026 som 5 SEPTEMBER, inte 9 maj — appen läste den europeiska vägen och flyttade tyst varje köp under den 13:e till fel månad. Ordningen läses nu ur hela kolumnen, visas i importsteget med ett exempel, och går att ändra när filen inte själv avgör den',
        'Filer utan kolumnnamn fungerar också. Wells Fargo exporterar inga, och appen tog då första transaktionen för en rubrikrad — den försvann utan ett ord. Nu känns det igen: en rubrik innehåller inte ett datum och ett belopp',
        'Och en återbetalning räknas nu som en återbetalning. Ett köp på 100 kr och 20 kr tillbaka från samma ställe låg tidigare som två utgifter och blev 120 kr — nu står de som två rader som summerar till 80 kr, vilket är vad du faktiskt betalade',
        'Omöjliga datum stoppas vid dörren. Den 31 februari finns inte, men JavaScript gör tyst om den till 3 mars — sådana rader hoppas nu över och räknas i importens sammanfattning i stället för att landa i fel månad',
        'Och en halv import kan inte bli kvar. Säger enhetens lagring nej mitt i en import över flera månader återställs allt till hur det såg ut innan, och appen säger till — tidigare kunde en månad vara sparad och nästa inte. Har du appen öppen i två flikar upptäcker den nu den andras ändringar och laddar om i stället för att skriva över dem',
        'Appen startar nu på enhetens språk i stället för alltid på svenska. Läser din telefon engelska eller spanska möts du av det från första skärmen — tidigare fick alla svenska och fick leta i menyn. Valutasymbolen följer samma signal (den räknar fortfarande aldrig om några belopp)',
        'Typsnittet ligger nu i appen i stället för att hämtas från Google. Den gamla raden skickade din IP-adress till en tredje part vid varje start — det enda som lämnade enheten i en app vars hela löfte är att ingenting gör det. Nu hämtas ingenting alls: 266 förfrågningar vid start, samtliga till appen själv',
        'Ny: Integritet under ⚙ Meny. Vad appen gör med dina uppgifter, i klartext på alla tre språken — och samma text som en fristående sida för App Store. Ett test håller de två versionerna till samma ord, för en integritetspolicy som säger olika saker på olika ställen är sämre än ingen alls',
        'Och rader där kortterminalen inte kunde skriva svenska bokstäver. Vissa banker skickar Ö som @ och Ä som # — "AB GR@NA LUNDS" är Gröna Lund, och sorteras nu som om det stod rätt',
        'Nytt: Bara utfall. Plan- och skillnadskolumnerna försvinner och kategorierna sorteras efter var det går mest pengar. För när frågan inte är "höll jag budgeten" utan "var blöder det"',
        'Allt detta sker på din enhet. Det är en lista och dina egna rättelser — ingen modell som laddas ner, ingenting som skickas iväg',
        'Importerar du samma fil igen läggs ingenting till dubbelt. Men två likadana köp samma dag räknas fortfarande som två, för det är precis vad de är',
        'Nytt: en flik för uppföljning. Din plan står bredvid vad som faktiskt hände, kategori för kategori. Lägg till det du betalat för hand — varje siffra går att fälla ut och läsa rad för rad, och en post du skrivit själv är märkt som sådan',
        'Fyller du inte i en kategori står den som – och inte som 0 kr. Att inte ha registrerat något är inte samma sak som att inte ha spenderat något',
        'Nytt: appen berättar varför den ser ut som den gör. Ett brev från mig om varför budgeten ligger lokalt på din enhet, och vart den är på väg',
        'Det visas första gången du öppnar appen, och finns kvar under ⚙ → Om appen. Har du använt appen förut hittar du det där — förstagångshälsningen visas aldrig för någon som redan har en budget',
        'Nytt: Ångra. Varje knapp som förstör har nu en väg tillbaka — Återställ månad, Rensa månad, en import, en inläst säkerhetskopia, en borttagen kategori, och de tre som kopierar en budget. Den sista är den viktigaste: "→ Alla återstående" skriver över varje kvarvarande månad i året, upp till elva färdiga budgetar på ett tryck',
        'Knappen dyker upp direkt efter åtgärden och ligger kvar i ⚙ Meny med vad som gjordes och när — för ångern kommer ibland en vecka senare. Tio steg sparas',
        'Det som sparas är inte en kopia av appen utan de värden som faktiskt ändrades. Tio steg kostar därför några kilobyte i stället för tio kopior av allt — och de följer inte med i en säkerhetskopia, som ska innehålla dina siffror och inte en andra uppsättning gamla',
        'En tom kategori kostar ingen plats i historiken. Bara en som innehöll något, för strukturen är det som tog tid att bygga',
        'Dialogerna säger inte längre "kan inte ångras", eftersom det inte längre är sant',
        'Nytt: Sortera, i Uppföljning. Det som hamnade i Övrigt visas som en lista med störst belopp först och ett förslag per ställe — ett tryck flyttar hela stället och lär sig valet. På ett riktigt kontoutdrag var det 34 poster, hopvikta i en rad du själv fick komma på att öppna',
        'Störst belopp först, inte flest poster: åtta kaffe och en hyra är inte lika mycket värda att trycka på',
        'Förslaget säger varifrån det kommer — din egen regel, hur du gjort förut, eller den inbyggda listan. Din egen historik väger tyngre än listan. Saknas kategorin helt erbjuds den att skapas, aldrig bakom ryggen på dig',
        'Menyn visar nu alltid när du senast säkerhetskopierade: "Senaste säkerhetskopia: 17 september 2026", eller "aldrig". Du ska inte behöva gissa hur utsatt du är, och svaret är ett datum',
        'Efter ett halvår byter påminnelsen ton. Den lugna raden säger "rekommenderas"; den här säger vad som faktiskt står på spel om enheten försvinner — och har kortare tålamod, två dagar i stället för sju, eftersom den lugna vid det laget har viftats bort ett dussin gånger',
        'Eskaleringen gäller även dig som aldrig säkerhetskopierat. Utan en backup finns inget datum att räkna på, så appen räknar från dagen den först frågade — ett halvår av att bli tillfrågad utan att göra det är precis det fallet varningen finns för',
        'Första starten visar tre korta kort i stället för brevet: var din data hamnar, vad du gör först, och vad du får ut av det. Brevet ligger kvar under 💬 Om appen — det var fyra skärmhöjder på en telefon, och det är inte en första skärm',
        'Nytt: en guide i Uppföljning. Tryck på ? bredvid Importera — där står vad fliken är till för, hur löneperioden räknas, vad Övrigt och Överföring betyder, och vad verktygen gör',
        'Guiden säger också rakt ut vad sorteraren är: ingen AI, ingenting som laddas ner, utan en lista på 863 namn plus dina egna rättelser. Den är inte smart — den är noggrann, och den lyssnar på dig. Det är lättare att lita på något man förstår',
      ],
      en: [
        'New: import your bank statement as a CSV file. The app reads the file on your device — it is never sent anywhere — and works out for itself which columns hold the date, the text and the amount. If the guess is wrong you correct it once, and the app then remembers the layout and never asks again for that bank',
        'The review groups by place rather than listing every row: six ICA purchases are one decision, not six. Entries you give no category are not imported',
        'Every entry lands in the month its own date belongs to, so a file spanning two months fills both — and the app says which ones it touched',
        'A bank statement is usually last month’s, so the month that changes is rarely the one in front of you. The summary now carries a button that takes you there',
        'Entries whose category that month’s budget does not have are collected under "Outside the budget" rather than not being drawn at all. Import into a month you have not budgeted yet and the money is still there, still shown and still counted',
        'New: the app sorts the statement for you. It ships with a ready-made Swedish list — ICA, Willys, SL, Västtrafiken, Telenor, Apoteket, Pressbyrån, Espresso House and a few hundred more — so even the first import arrives mostly filled in',
        'Correct a category and it remembers, and next time your correction outweighs the list’s guess. The same shop is recognised even when the bank prints a different till number, and a Swedish compound word is taken apart to find the place inside it',
        'When a category you need is missing, the app offers to create it. The offer carries a dashed border until you press Import — and the category is created in the month the entries land in, not the one you happen to be looking at',
        'It never guesses at a transfer, a withdrawal fee or a Swish to a person. There is no shop there to recognise, and a wrong category costs more than an empty one',
        'The list has an international half and a Swedish one. Netflix, Lidl, IKEA, Ryanair, Zalando, MediaMarkt and a couple of hundred more are recognised whatever country you are in, with the Swedish half on top. A country is added when there is a real file to check it against, never from memory',
        'The import reads more European files: German dates like 31.08.26, amounts with the currency beside them like "45,20 PLN", and exports whose column headings the app has never seen — a column is then recognised by what it holds rather than by what it is called',
        'A statement’s columns can be changed afterwards. If the app learned the wrong layout for a bank it was stuck with it for good — there is now a "Change columns" button in the review, and it forgets the stored guess as it goes back',
        'A new button under Follow-up: clear the whole month’s actuals at once. The way back from importing the wrong file, instead of removing a hundred entries one at a time',
        '"Reset month" now says what it does. It resets the budget and leaves the recorded actuals alone — it used to say it cleared the month, and the entries stayed behind without a word',
        'The pay period now governs Follow-up. If you live 25→24, the rent and every standing charge land in the right budget month — on one real statement 74.5% of the spending had been filed under the wrong month. The budget’s amounts are untouched, and with the period off everything works exactly as before',
        'The import now reads the TRANSACTION date, not the booking date. A bank books a salary the evening before so the money is there on payday — on a real statement that was the only one of 107 rows to land in the wrong budget month, and it was the salary: the largest figure of the month, on the wrong side of the line',
        'The period steps over weekends by itself. When the 25th falls on a Saturday the salary arrives on the Friday — four months of twelve in 2026. Nothing to set: the app counts from the day the money actually came',
        'And when it is still wrong, you can pin a single period by hand under Follow-up. That month only; the rest keep following the rule',
        'Change the start day and the recorded entries move with it, counted out loud first. Nothing is lost — every entry carries its own date, so the re-filing is exact and can be run again',
        'New in Follow-up: choose Month, 3, 6 or 12 months. Plan and actuals are summed over the span — and a month with no budget is not counted as zero, it is said out loud',
        'Over several months a category is grouped by place rather than by date. "Espresso House, 8 entries, 448 kr" instead of eight scattered lines — the view a bank statement never gives you, because it sorts by date',
        'The grouping by place is now clickable: "Espresso House, 4 entries, 224 kr" unfolds into its dates, where a figure can be corrected or removed. Or choose By date if you would rather read it in time order',
        'The sorter now reads descriptions the bank cut short. Card rows stop at sixteen characters, so the last word is often a fragment — "Do Re Mi Restaur", "ANTIKA RESTAURAN", "2627705203 Nordn" are recognised anyway. Only as a last resort: a whole-word match always beats a fragment',
        'The import no longer throws anything away. What the app cannot place goes to "Other", and transfers between your own accounts to "Transfers" — they used to simply vanish, and on a real statement that was 173 of 471 transactions you then had no way to reach',
        'Transfers do NOT count as spending. Moving 5 000 to your own savings account is not spending 5 000 — the row sits below the total, outside it. On a real statement counting them would have inflated a month from 29 927 to 58 514 kr',
        'And a whole place can now be moved to the right category from inside Follow-up — the entire group at once, and the choice is learned so the next import lands it correctly',
        'And when the category you need does not exist, you can make it right there — "+ New category…" in the same menu. It is added to every month in view, so the entries you move into it are not left homeless in the others',
        'A new standard category: Loans & Credit. Student loans, mortgages, amortisation and buy-now-pay-later fitted none of the other seven — a CSN repayment landed in Other with nowhere to move it. CSN, Kronofogden, SBAB, Klarna, Qliro and thirty more are now recognised automatically',
        'The sorter has two more lists: American and Spanish. Walmart, Kroger, Walgreens, Chevron, Mercadona, Renfe, Iberdrola, Movistar and a couple of hundred others. The Swedish list is still the only one measured against a real statement — the two new ones are a reasonable first guess, and it is after your first correction that it gets genuinely good, in any country',
        'And the parser now reads American files correctly. Chase and Wells Fargo write 09/05/2026 meaning 5 SEPTEMBER, not 9 May — the app read it the European way and silently moved every purchase below the 13th into the wrong month. The order is now read from the whole column, shown in the import step with a worked example, and can be changed when the file itself cannot settle it',
        'Files with no column names work too. Wells Fargo exports none, and the app took the first transaction for a heading — it vanished without a word. A heading does not hold a date and an amount, and that is now how it is told apart',
        'And a refund now counts as a refund. A purchase of 100 kr and 20 kr back from the same place used to sit there as two expenses adding up to 120 kr — they now stand as two rows that come to 80 kr, which is what you actually paid',
        'Impossible dates are stopped at the door. There is no 31 February, but JavaScript quietly turns it into 3 March — such rows are now skipped and counted in the import summary instead of landing in the wrong month',
        'And half an import cannot be left behind. If the device storage says no partway through an import spanning several months, everything goes back to how it was and the app says so — previously one month could be saved and the next not. With the app open in two tabs it now notices the other tab\u2019s changes and reloads instead of overwriting them',
        'The app now opens in the device\u2019s language instead of always in Swedish. If your phone reads English or Spanish you get that from the first screen — everyone used to get Swedish and had to go hunting in the menu. The currency symbol follows the same signal (it still never converts an amount)',
        'The typeface now ships with the app instead of being fetched from Google. The old line sent your IP address to a third party on every start — the one thing that left the device in an app whose whole promise is that nothing does. Now nothing is fetched at all: 266 requests at startup, every one of them to the app itself',
        'New: Privacy under \u2699 Menu. What the app does with your data, in plain words in all three languages — and the same text as a standalone page for the App Store. A test holds the two copies to the same words, because a privacy policy that says different things in different places is worse than none',
        'And rows where the card terminal could not write Swedish letters. Some banks send Ö as @ and Ä as # — "AB GR@NA LUNDS" is Gröna Lund, and now sorts as though it were spelled properly',
        'New: Actuals only. The plan and difference columns go, and the categories sort by where the money actually goes. For when the question is not "did I keep to the budget" but "where is it bleeding"',
        'All of this happens on your device. It is a list and your own corrections — no model downloaded, nothing sent anywhere',
        'Importing the same file again adds nothing twice. But two identical purchases on the same day still count as two, because that is exactly what they are',
        'New: a follow-up tab. Your plan sits beside what actually happened, category by category. Add what you paid by hand — every figure can be unfolded and read line by line, and an entry you typed yourself is marked as such',
        'A category you have not filled in shows – rather than 0 kr. Not having recorded something is not the same as not having spent anything',
        'New: the app explains why it works the way it does. A letter from me about why your budget lives locally on your device, and where it is heading',
        'It appears the first time you open the app, and stays available under ⚙ → About the app. If you have used the app before you will find it there — the first-run greeting never shows to someone who already has a budget',
        'New: Undo. Every button that destroys now has a way back — Reset month, Clear month, an import, a restored backup, a deleted category, and the three that copy a budget. That last one matters most: "→ All remaining" writes over every month left in the year, up to eleven finished budgets in one tap',
        'The button appears right after the action and stays in the ⚙ Menu with what was done and when — because regret sometimes arrives a week later. Ten steps are kept',
        'What is kept is not a copy of the app but the values that actually changed. Ten steps therefore cost a few kilobytes instead of ten copies of everything — and they do not travel in a backup, which should hold your figures, not a second set of older ones',
        'An empty category costs nothing in the history. Only one that held something, because the structure is the part that took the effort',
        'The dialogs no longer say "cannot be undone", because it is no longer true',
        'New: Sort them, in Follow-up. Whatever landed in Övrigt is shown as a list, biggest first, with a proposal per place — one tap moves the whole place and learns the choice. On a real statement that was 34 entries, folded inside a row you had to think to open',
        'Ordered by money, not by count: eight coffees and one rent bill are not equally worth a tap',
        'The proposal says where it came from — your own rule, what you did before, or the built-in list. Your own history outranks the list. When the category is missing entirely it is offered, never created behind your back',
        'The menu now always shows when you last backed up: "Last backup: 17 September 2026", or "never". You should not have to guess how exposed you are, and the answer is a date',
        'After six months the reminder changes its tone. The quiet line says "recommended"; this one says what is actually at stake if the device goes — and has shorter patience, two days instead of seven, because by then the quiet one has been waved away a dozen times',
        'The escalation reaches people who have never backed up at all. With no backup there is no date to age, so the app counts from the day it first asked — six months of being asked without doing it is exactly the case the warning is for',
        'The first run shows three short cards instead of the letter: where your data goes, what to do first, and what you get out of it. The letter is still there under 💬 About the app — it ran four screen-heights on a phone, and that is not a first screen',
        'New: a guide in Follow-up. Tap the ? beside Import — it says what the tab is for, how the pay period is counted, what Övrigt and Transfer mean, and what the tools do',
        'The guide also says plainly what the sorter is: not an AI, nothing downloaded, but a list of 863 names plus your own corrections. It is not clever — it is careful, and it listens to you. It is easier to trust something you understand',
      ],
      es: [
        'Nuevo: importa tu extracto bancario como archivo CSV. La app lee el archivo en tu dispositivo — nunca se envía a ningún sitio — y deduce sola qué columnas son la fecha, el texto y el importe. Si acierta mal lo corriges una vez, y la app recuerda la disposición y no vuelve a preguntar para ese banco',
        'La revisión agrupa por sitio en lugar de listar cada fila: seis compras en ICA son una decisión, no seis. Los movimientos sin categoría no se importan',
        'Cada movimiento cae en el mes al que pertenece su propia fecha, así que un archivo que abarca dos meses llena ambos — y la app dice cuáles tocó',
        'Un extracto suele ser del mes pasado, así que el mes que cambia rara vez es el que tienes delante. El resumen lleva ahora un botón que te lleva allí',
        'Los movimientos cuya categoría no existe en el presupuesto de ese mes se agrupan en "Fuera del presupuesto" en vez de no dibujarse. Importa a un mes que aún no has presupuestado y el dinero sigue ahí, se ve y cuenta',
        'Nuevo: la app ordena el extracto por ti. Viene con una lista sueca ya hecha — ICA, Willys, SL, Västtrafiken, Telenor, Apoteket, Pressbyrån, Espresso House y unos cientos más — así que hasta la primera importación llega casi rellena',
        'Si corriges una categoría lo recuerda, y la próxima vez tu corrección pesa más que la conjetura de la lista. Reconoce la misma tienda aunque el banco imprima otro número de caja',
        'Cuando falta una categoría que hace falta, la app propone crearla. La propuesta lleva borde discontinuo hasta que pulsas Importar — y la categoría se crea en el mes donde caen los movimientos, no en el que estás mirando',
        'Nunca adivina sobre una transferencia, una comisión o un Swish a una persona. Ahí no hay tienda que reconocer, y una categoría equivocada cuesta más que una vacía',
        'La lista tiene una parte internacional y otra sueca. Netflix, Lidl, IKEA, Ryanair, Zalando, MediaMarkt y un par de cientos más se reconocen estés donde estés, con la parte sueca encima. Un país se añade cuando hay un archivo real con el que comprobarlo, nunca de memoria',
        'La importación lee más archivos europeos: fechas alemanas como 31.08.26, importes con la moneda al lado como "45,20 PLN", y exportaciones cuyos encabezados la app no ha visto nunca — entonces la columna se reconoce por lo que contiene y no por cómo se llama',
        'Las columnas de un extracto se pueden cambiar después. Si la app aprendía mal la disposición de un banco se quedaba así para siempre — ahora hay un botón "Cambiar columnas" en la revisión, y olvida la suposición guardada',
        'Nuevo botón en Seguimiento: borrar de una vez todos los movimientos del mes. La vuelta atrás tras importar el archivo equivocado, en lugar de eliminar cien movimientos uno a uno',
        '"Restablecer mes" ahora dice lo que hace. Reinicia el presupuesto y no toca los movimientos registrados — antes decía que borraba el mes y los movimientos se quedaban sin avisar',
        'El periodo de nómina ahora rige Seguimiento. Si vives del 25 al 24, el alquiler y todos los gastos fijos caen en el mes correcto — en un extracto real el 74,5 % del gasto estaba en el mes equivocado. Los importes del presupuesto no se tocan, y con el periodo desactivado todo funciona como antes',
        'La importación lee ahora la fecha de TRANSACCIÓN, no la de contabilización. El banco contabiliza la nómina la tarde antes para que el dinero esté el día de pago — en un extracto real fue la única de 107 filas que cayó en el mes equivocado, y era la nómina: la cifra más grande del mes, al lado equivocado de la línea',
        'El periodo salta los fines de semana solo. Si el 25 cae en sábado, la nómina llega el viernes — cuatro meses de doce en 2026. No hay nada que configurar: la app cuenta desde el día que llegó el dinero',
        'Y si aun así falla, puedes fijar un periodo a mano en Seguimiento. Solo ese mes; los demás siguen la regla',
        'Si cambias el día de inicio, los movimientos registrados se mueven contigo, contados en voz alta antes. No se pierde nada — cada movimiento lleva su fecha, así que el traslado es exacto y repetible',
        'Nuevo en Seguimiento: elige Mes, 3, 6 o 12 meses. Plan y movimientos se suman en todo el periodo — y un mes sin presupuesto no cuenta como cero, se dice',
        'A lo largo de varios meses una categoría se agrupa por sitio y no por fecha. "Espresso House, 8 movimientos, 448 kr" en vez de ocho líneas sueltas — la vista que un extracto nunca te da, porque ordena por fecha',
        'La agrupación por sitio ahora se puede pulsar: "Espresso House, 4 movimientos, 224 kr" se despliega en sus fechas, donde puedes corregir o eliminar. O elige Por fecha si prefieres leerlo en orden cronológico',
        'El clasificador ahora lee descripciones que el banco ha cortado. Las filas de tarjeta se cortan a dieciséis caracteres, así que la última palabra suele quedar a medias — "Do Re Mi Restaur", "ANTIKA RESTAURAN", "2627705203 Nordn" se reconocen igual. Solo como último recurso: una palabra completa siempre gana',
        'La importación ya no descarta nada. Lo que la app no puede colocar va a "Otros", y las transferencias entre tus propias cuentas a "Transferencias" — antes desaparecían, y en un extracto real eran 173 de 471 movimientos que luego no podías alcanzar',
        'Las transferencias NO cuentan como gasto. Mover 5 000 a tu propia cuenta de ahorro no es gastar 5 000 — la fila va debajo del total, fuera de él. En un extracto real contarlas habría inflado un mes de 29 927 a 58 514 kr',
        'Y ahora puedes mover un sitio entero a la categoría correcta desde Seguimiento — todo el grupo de una vez, y la elección se recuerda para la próxima importación',
        'Y cuando falta la categoría que necesitas, puedes crearla ahí mismo — "+ Categoría nueva…" en el mismo menú. Se añade a todos los meses en vista, para que los movimientos que traslades no queden huérfanos en los demás',
        'Nueva categoría estándar: Préstamos y créditos. Los préstamos estudiantiles, hipotecas, amortización y el compra-ahora-paga-después no encajaban en ninguna de las otras siete. Ahora se reconocen CSN, Kronofogden, SBAB, Klarna, Qliro, Cofidis, Cetelem y treinta más',
        'El clasificador tiene dos listas más: americana y española. Walmart, Kroger, Walgreens, Chevron, Mercadona, Renfe, Iberdrola, Movistar y un par de cientos más. La lista sueca sigue siendo la única medida contra un extracto real — las dos nuevas son una primera aproximación razonable, y es tras tu primera corrección cuando funciona de verdad, en cualquier país',
        'Y el lector interpreta bien los archivos americanos. Chase y Wells Fargo escriben 09/05/2026 como 5 de SEPTIEMBRE, no 9 de mayo — la app lo leía a la europea y movía en silencio cada compra anterior al día 13 al mes equivocado. El orden se lee ahora de toda la columna, se muestra con un ejemplo y se puede cambiar cuando el archivo no lo aclara',
        'Los archivos sin nombres de columna también funcionan. Wells Fargo no los exporta, y la app tomaba el primer movimiento como encabezado — desaparecía sin avisar. Un encabezado no lleva fecha ni importe, y así se distingue ahora',
        'Y una devolución ahora cuenta como devolución. Una compra de 100 kr y 20 kr de vuelta del mismo sitio figuraban como dos gastos que sumaban 120 kr — ahora son dos filas que suman 80 kr, que es lo que pagaste de verdad',
        'Las fechas imposibles se paran en la puerta. El 31 de febrero no existe, pero JavaScript lo convierte en silencio en el 3 de marzo — esas filas se omiten y se cuentan en el resumen de la importación en vez de acabar en el mes equivocado',
        'Y ya no puede quedarse media importación. Si el almacenamiento del dispositivo falla a mitad de una importación de varios meses, todo vuelve a como estaba y la app lo dice — antes podía quedar un mes guardado y el siguiente no. Con la app abierta en dos pestañas ahora detecta los cambios de la otra y recarga en vez de sobrescribirlos',
        'La app ahora abre en el idioma del dispositivo en vez de siempre en sueco. Si tu teléfono lee español o inglés lo tendrás desde la primera pantalla — antes todo el mundo recibía sueco y tenía que buscar en el menú. El símbolo de moneda sigue la misma señal (nunca convierte importes)',
        'La tipografía ahora viaja con la app en vez de descargarse de Google. La línea anterior enviaba tu IP a un tercero en cada arranque — lo único que salía del dispositivo en una app cuya promesa es que nada sale. Ahora no se descarga nada: 266 peticiones al arrancar, todas a la propia app',
        'Nuevo: Privacidad en \u2699 Menú. Qué hace la app con tus datos, en lenguaje claro en los tres idiomas — y el mismo texto como página independiente para la App Store. Un test mantiene las dos copias con las mismas palabras, porque una política que dice cosas distintas en sitios distintos es peor que ninguna',
        'Y filas donde el terminal no pudo escribir letras suecas. Algunos bancos mandan Ö como @ y Ä como # — "AB GR@NA LUNDS" es Gröna Lund, y ahora se clasifica como si estuviera bien escrito',
        'Nuevo: Solo movimientos. Desaparecen las columnas de plan y diferencia, y las categorías se ordenan por dónde va más dinero. Para cuando la pregunta no es "¿cumplí el presupuesto?" sino "¿por dónde se escapa?"',
        'Todo esto ocurre en tu dispositivo. Es una lista y tus propias correcciones — ningún modelo descargado, nada enviado a ningún sitio',
        'Importar el mismo archivo otra vez no añade nada por duplicado. Pero dos compras idénticas el mismo día siguen contando como dos, porque es exactamente lo que son',
        'Nuevo: una pestaña de seguimiento. Tu plan aparece junto a lo que pasó de verdad, categoría por categoría. Añade a mano lo que pagaste — cada cifra se puede desplegar y leer línea por línea, y un movimiento escrito por ti va marcado como tal',
        'Una categoría que no has rellenado muestra – en vez de 0 kr. No haber registrado algo no es lo mismo que no haber gastado nada',
        'Nuevo: la app explica por qué funciona como funciona. Una carta mía sobre por qué tu presupuesto vive localmente en tu dispositivo, y hacia dónde va',
        'Aparece la primera vez que abres la app y queda disponible en ⚙ → Sobre la app. Si ya has usado la app lo encontrarás ahí — el saludo de bienvenida nunca se muestra a quien ya tiene un presupuesto',
        'Nuevo: Deshacer. Todos los botones que destruyen tienen ya vuelta atrás — Reiniciar mes, Vaciar mes, una importación, una copia restaurada, una categoría eliminada y los tres que copian un presupuesto. El último es el que más importa: "→ Todos los restantes" sobrescribe cada mes que queda del año, hasta once presupuestos terminados de un toque',
        'El botón aparece justo después de la acción y se queda en el ⚙ Menú con qué se hizo y cuándo — porque el arrepentimiento a veces llega una semana después. Se guardan diez pasos',
        'Lo que se guarda no es una copia de la app sino los valores que de verdad cambiaron. Diez pasos cuestan unos kilobytes en vez de diez copias de todo — y no viajan en la copia de seguridad, que debe llevar tus cifras y no un segundo juego de las antiguas',
        'Una categoría vacía no ocupa sitio en el historial. Solo una que contenía algo, porque la estructura es lo que costó construir',
        'Los diálogos ya no dicen "no se puede deshacer", porque ya no es cierto',
        'Nuevo: Clasificar, en Seguimiento. Lo que acabó en Övrigt se muestra como una lista, de mayor a menor, con una propuesta por sitio — un toque mueve el sitio entero y aprende la elección. En un extracto real eran 34 movimientos, plegados en una fila que tenías que acordarte de abrir',
        'Ordenado por dinero, no por número: ocho cafés y un alquiler no merecen el mismo toque',
        'La propuesta dice de dónde viene — tu propia regla, lo que hiciste antes, o la lista incorporada. Tu historial pesa más que la lista. Si falta la categoría se ofrece crearla, nunca a tus espaldas',
        'El menú muestra siempre cuándo hiciste la última copia: "Última copia de seguridad: 17 de septiembre de 2026", o "nunca". No deberías tener que adivinar lo expuesto que estás, y la respuesta es una fecha',
        'A los seis meses el recordatorio cambia de tono. La línea tranquila dice "recomendada"; esta dice qué está realmente en juego si el dispositivo desaparece — y tiene menos paciencia, dos días en vez de siete, porque a esas alturas la tranquila se ha descartado una docena de veces',
        'La escalada alcanza también a quien nunca ha hecho una copia. Sin copia no hay fecha que envejecer, así que la app cuenta desde el día en que preguntó por primera vez — medio año preguntando sin resultado es justo el caso para el que existe el aviso',
        'El primer arranque muestra tres tarjetas cortas en vez de la carta: dónde va tu información, qué hacer primero y qué sacas de ello. La carta sigue en 💬 Sobre la app — ocupaba cuatro pantallas en un teléfono, y eso no es una primera pantalla',
        'Nuevo: una guía en Seguimiento. Pulsa el ? junto a Importar — explica para qué sirve la pestaña, cómo se cuenta el periodo de cobro, qué significan Övrigt y Transferencia, y qué hacen las herramientas',
        'La guía también dice sin rodeos qué es el clasificador: no es una IA, no descarga nada, es una lista de 863 nombres más tus propias correcciones. No es listo — es cuidadoso, y te hace caso. Es más fácil confiar en algo que entiendes',
      ],
    },
  },
  {
    version: '1.11.0',
    date: '2026-08-06',
    title: { sv: 'Ett år i Anpassad — och siffror som stämmer', en: 'A year in Custom — and figures that match', es: 'Un año en Personalizado — y cifras que coinciden' },
    items: {
      sv: [
        'Nytt: "Hämta från <förra månaden>" i menyn under Kopiera budget — samma sak som Anpassad layout redan kunde, nu även i Klassisk och Kombinerad',
        'Kopiering flyttar bara inkomster och utgifter, aldrig sparandet. Sparandet är ett registrerat saldo, så en kopia hade fått månaden att påstå ett sparande du aldrig fyllt i — Årsfliken visade "0 kr" i stället för "ej registrerat". Det gällde även "Nästa månad", som nu är rättad',
        'Har månaden redan belopp får du en fråga först, och en tom föregående månad hämtas inte alls',
        'Diagramtypen "Trend" är borttagen ur Anpassad layout. Den ritade alltid staplar, oavsett att den stod som vald. Befintliga block som använder den visas som Staplar och behåller namn, rader, färger, storlek och position',
        'Backup vägrar nu en fil med diagraminställningar appen inte kan visa, i stället för att importera dem och lämna inställningspanelen tom',
        'Nytt: Anpassad layout har en årsöversikt. Växla mellan 📋 Budget och 📅 År högst upp — hela året med in, ut, sparat och kvar, plus totaler. Tidigare såg du bara en månad i taget, eftersom Anpassad döljer flikraden',
        'I årsöversikten visas en månad du aldrig fyllt i som "–", inte som 0 kr. Sparat summeras över året, eftersom Anpassad lagrar vad du la undan varje månad',
        'Nytt: duplicera ett block med ⧉ i redigeringsläget. Kopian får samma rader, färger och diagraminställningar och hamnar direkt efter originalet — men utan belopp, så du fyller i den på nytt',
        'Nytt: färdiga block i "Lägg till block" — Boende, Mat, Transport och Sparande, med rätt typ och förnamngivna rader. De följer språkbytet precis som appens övriga standardnamn',
        'Nytt: en rad under korten som säger något om månaden i stället för att bara visa siffror — största utgiftsposten, hur mycket du la undan, eller ett underskott. Är du nära ett sparmål eller har sparandet växt flera månader i rad står det där i stället',
        'Nytt: en rad kan betalas per kvartal eller per år. Skriv beloppet du faktiskt betalar — 4 800 kr för hemförsäkringen — och markera raden "Per år". Budgeten räknar 400 kr i månaden i stället för att låta januari se ut som en katastrof. Rör du ingenting är allt månadsvis som förut',
        'Nytt: löneperiod som text under månaden. Ange vilken dag din period börjar, så skriver appen "25 dec – 24 jan" under varje månad. Vill du hellre kalla en enskild månad något eget klickar du på texten och skriver — rensar du fältet är du tillbaka på den automatiska. Det är bara en etikett: inga belopp påverkas',
        'Ändrat: "Per år" delar inte längre beloppet på tolv. En årsprenumeration dras i sin helhet den månad du betalar den, så budgeten stämmer med kontot just då. Nytt val: Engångskostnad',
        'Rader som inte återkommer varje månad följer inte längre med när du kopierar budgeten framåt — annars hade februari fått en kostnad som aldrig inträffar. Du lägger tillbaka dem när de förfaller',
        'Rättat: kopiering skriver inte längre över en månad utan att fråga. Frågan namnger både månaden och källan, och "Alla återstående" räknar först hur många som berörs. Avbryter du skrivs ingenting',
        'Rättat: Sparande erbjöd ett periodval, vilket fick samma konto att visa 12 000 kr och 1 000 kr samtidigt. Ett saldo är vad du har, inte något som dras',
        'Rättat: Anpassad layouts årsöversikt ändrade historiken när du redigerade dagens layout. Varje månad sparar nu sin egen struktur, så september står kvar även om du tar bort blocket i oktober',
        'Rättat: årsöversikten i Anpassad var hoptryckt till en smal spalt, löneperiodens startdag 1 visade föregående månad, och en skadad periodmarkering kunde ge tomma summor',
        'Rättat: "Hämta från föregående månad" kunde tömma en färdig budget. En månad som bara innehöll sparande eller en egen periodtext räknades som en budget att hämta — nu krävs riktigt budgetinnehåll, annars händer ingenting',
        'Custom-månader som spelades in innan appen började spara sin struktur får den nu i efterhand. Utan den klassades gamla månader om varje gång du ändrade dagens layout. Inga belopp rörs',
        'Att ta bort en enskild rad i Custom frågar nu först, precis som ett helt block gjorde — och varningen räknar även månaden du står i',
        'Varningen förklarar vad som faktiskt händer: raderna försvinner ur månadsbudgeten men beloppen räknas kvar i årsöversikten, så de två vyerna visar olika siffror',
        '"Rensa belopp" tar nu även bort de strukturanteckningar som hörde till beloppen, i stället för att lämna dem kvar utan något att beskriva',
        'Rättat: menyn gick inte att scrolla på datorn. Var fönstret för lågt hamnade dess nedre del utanför skärmen, och eftersom sidhuvudet är fastnålat hjälpte det inte att scrolla sidan — Importera data och hela Farozonen gick helt enkelt inte att nå. Menyn håller sig nu innanför fönstret och listan scrollar',
        'Rättat: en rad som inte är månatlig skrev ut sin period två gånger — "Engångskostnad" i väljaren och "engångskostnad" bredvid — och väljaren var dessutom avklippt mitt i ordet. Perioden står nu på ett ställe, och hela ordet får plats',
        'Rättat: hade du appen öppen i två flikar kunde den ena tyst skriva över den andras ändringar. Höjde du lönen i en flik och ändrade hyran i den andra fanns efteråt bara hyran kvar, utan någon varning. Flikarna håller sig nu uppdaterade med varandra, så båda ändringarna överlever',
        'Rättat: i Anpassad layout erbjöd menyn Kopiera budget och Återställ månad — men de arbetade på den klassiska budgeten, alltså data du inte såg, och rapporterade ändå att det gått bra. De visas nu bara i Klassisk och Kombinerad, där de hör hemma',
        'Rättat: en trasig språk- eller valutainställning gjorde appen helt blank vid start, utan meny att ändra tillbaka med. Båda kontrolleras nu, både när appen startar och när en backup importeras — en fil med ett okänt språk avvisas i stället för att först ersätta din budget',
        'Nytt: vägrar webbläsaren spara — fullt utrymme, eller lagring avstängd — säger appen det rakt ut i stället för att låta ändringen se sparad ut. Ändringen står kvar på skärmen, och därifrån kan du försöka igen eller exportera dina data',
        'Rättat: i Utgiftsfördelning räknades procenten mot inkomsten medan cirkeln ritades mot utgifterna. En ensam utgiftspost fyllde hela cirkeln och stod ändå som 45 %. Nu är båda andel av utgifterna',
        'Rättat: på mobil klipptes beloppen i sammanfattningskorten — 30 000,50 kr blev 30 000,5… Korten ligger nu två i bredd med Kvar under, så vanliga belopp med ören syns helt även på en 320 px skärm',
        'Rättat: årsöversiktens diagram jämförde olika sorters tal. Inkomst och utgifter är flöden, sparsaldot är ett saldo — men alla tre ritades som lika staplar, och en sparpott på 48 000 kr blev därför årets högsta stapel varje månad och tryckte ihop siffrorna diagrammet handlar om. Sparsaldot går nu som en linje på egen axel till höger',
        'Rättat: en månad du aldrig fyllt i stod som 0 kr i årsöversikten, alltså en månad utan inkomst och utan utgifter. Nu står det – precis som sparkolumnen redan gjorde. En månad du byggt men lämnat på noll räknas fortfarande som en riktig nolla',
        'Rättat: Måluppfyllnad visade 0 % innan du skapat något mål — en poäng i en tävling du inte börjat. Nu står det – med en förklaring, som de andra korten bredvid',
        'Ändrat: på skärmar mellan 640 och 900 px låg sammanfattningskorten staplade på varsin rad, så ett halvbrett fönster la mer höjd på tre tal än en telefon gör. De ligger nu tre i bredd och diagrammen syns utan att man scrollar',
      ],
      en: [
        'New: "Pull from <last month>" in the menu under Copy budget — what the Custom layout could already do, now in Classic and Combined too',
        'Copying moves income and expenses only, never savings. Savings is a recorded balance, so a copy made the month claim savings you never entered — the Year tab showed "0 kr" instead of "not recorded". That applied to "Next month" too, which is now fixed',
        'If the month already has amounts you get a confirmation first, and an empty previous month is never pulled',
        'The "Trend" chart type is gone from the Custom layout. It always drew bars despite showing as selected. Existing blocks using it now display as Bars and keep their name, rows, colors, size and position',
        'Backup now refuses a file holding chart settings the app cannot display, instead of importing them and leaving the settings panel blank',
        'New: the Custom layout has a year overview. Switch between 📋 Budget and 📅 Year at the top — the whole year with in, out, saved and left, plus totals. Until now you could only ever see one month, because Custom hides the tab bar',
        'In the year overview a month you never filled in shows "–", not 0 kr. Saved is summed across the year, because Custom stores what you set aside each month',
        'New: duplicate a block with ⧉ in edit mode. The copy keeps the same rows, colors and chart settings and lands right after the original — but without amounts, so you fill it in fresh',
        'New: ready-made blocks in "Add block" — Housing, Food, Transport and Savings, with the right type and pre-named rows. They follow a language switch like every other built-in name',
        'New: a line under the summary cards that says something about the month instead of only showing figures — your largest expense, how much you set aside, or a deficit. If a goal is within reach or your savings have grown several months running, it says that instead',
        'New: a row can fall due quarterly or yearly. Type the amount you actually pay — 4,800 kr for the insurance — and mark the row "Yearly". The budget counts 400 kr a month instead of making January look like a disaster. Touch nothing and everything stays monthly as before',
        'New: a pay-period line under the month. Set the day your period starts and the app writes "25 Dec – 24 Jan" under every month. Prefer your own words for one month? Click the text and type — clear the field to go back to automatic. It is only a label: no amounts change',
        'Changed: "Yearly" no longer divides the amount by twelve. An annual subscription is charged in full in the month you pay it, so the budget matches your account that month. New option: One-off',
        'Rows that do not recur monthly are no longer carried along when you copy the budget forward — otherwise February would show a charge that never happens. You add them back when they fall due',
        'Fixed: copying no longer overwrites a month without asking. The prompt names the month and the source, and "All remaining" counts how many are affected first. Cancel and nothing is written',
        'Fixed: the Savings tab offered a period control, which made one account show 12,000 kr and 1,000 kr at once. A balance is what you have, not something that gets charged',
        'Fixed: the Custom year overview changed history when you edited today\'s layout. Each month now records its own structure, so September stands even if you delete the block in October',
        'Fixed: the Custom year view was squeezed into a narrow column, a pay period starting on the 1st showed the previous month, and a corrupt period marking could empty a total',
        'Fixed: "Pull from last month" could empty a finished budget. A month holding only savings or just a period label counted as a budget to pull from — it now needs real budget content, and otherwise nothing happens',
        'Custom months recorded before the app started saving their structure are given it retroactively. Without it, editing today\'s layout reclassified older months. No amounts are touched',
        'Deleting a single row in Custom now asks first, exactly as deleting a whole block did — and the warning counts the month you are standing in as well',
        'The warning explains what actually happens: the rows leave the monthly budget but the amounts stay counted in the year overview, so the two views show different figures',
        '"Clear amounts" now also removes the structure notes that belonged to those amounts, instead of leaving them behind with nothing to describe',
        'Fixed: the menu could not be scrolled on desktop. In a short window its lower half fell outside the screen, and because the header is pinned, scrolling the page did not help — Import data and the whole danger zone were simply unreachable. The menu now stays inside the window and the list scrolls',
        'Fixed: a row that is not monthly stated its period twice — "One-off" in the picker and "one-off cost" beside it — and the picker was clipped mid-word. The period is named in one place now, and the whole word fits',
        'Fixed: with the app open in two tabs, one could silently overwrite the other. Raise the salary in one tab and change the rent in the other, and only the rent survived — with no warning. Tabs now keep up with each other, so both edits stand',
        'Fixed: in the Custom layout the menu offered Copy budget and Reset month — but they acted on the Classic budget, data you were not looking at, and still reported success. They now appear only in Classic and Combined, where they belong',
        'Fixed: a damaged language or currency setting left the app completely blank at start, with no menu left to change it back. Both are now checked, at startup and on import — a backup carrying an unknown language is refused instead of first replacing your budget',
        'New: if the browser refuses to save — full storage, or storage switched off — the app says so instead of letting the change look saved. The change stays on screen, and from there you can retry or export your data',
        'Fixed: in Expense distribution the percentage was measured against income while the circle was drawn from expenses. A lone expense filled the whole circle and was still labelled 45 %. Both are now a share of expenses',
        'Fixed: on mobile the summary amounts were cut off — 30 000,50 kr became 30 000,5… The cards now sit two across with Left below, so ordinary amounts with decimals are fully visible even on a 320 px screen',
        'Fixed: the year chart compared different kinds of number. Income and expenses are flows, the savings figure is a balance — but all three were drawn as equal bars, so a 48 000 kr pot became the tallest bar of the year every month and flattened the figures the chart is named after. The balance is now a line on its own axis on the right',
        'Fixed: a month you never filled in showed as 0 kr in the year overview — a month with no earnings and no spending. It now shows –, exactly as the savings column already did. A month you built and left at zero still counts as a real zero',
        'Fixed: Goal progress showed 0 % before you had created any goal — a score in a game you had not started. It now shows – with an explanation, like the cards beside it',
        'Changed: between 640 and 900 px the summary cards stacked one per row, so a half-width window spent more height on three numbers than a phone does. They now sit three across and the charts are visible without scrolling',
      ],
      es: [
        'Nuevo: "Traer de <mes anterior>" en el menú bajo Copiar presupuesto — lo que el diseño personalizado ya hacía, ahora también en Clásico y Combinado',
        'Copiar mueve solo ingresos y gastos, nunca el ahorro. El ahorro es un saldo registrado, así que una copia hacía que el mes afirmara un ahorro que nunca introdujiste — la pestaña Año mostraba "0 kr" en lugar de "no registrado". También ocurría con "Mes siguiente", ya corregido',
        'Si el mes ya tiene importes se te pregunta primero, y un mes anterior vacío nunca se trae',
        'El tipo de gráfico "Tendencia" se ha eliminado del diseño personalizado. Siempre dibujaba barras aunque apareciera como seleccionado. Los bloques existentes se muestran como Barras y conservan nombre, filas, colores, tamaño y posición',
        'La copia de seguridad ahora rechaza un archivo con ajustes de gráfico que la app no puede mostrar, en lugar de importarlos y dejar el panel vacío',
        'Nuevo: el diseño personalizado tiene una vista anual. Cambia entre 📋 Presupuesto y 📅 Año arriba — todo el año con entradas, salidas, ahorro y resto, más totales. Hasta ahora solo podías ver un mes, porque Personalizado oculta las pestañas',
        'En la vista anual, un mes que nunca rellenaste muestra "–", no 0 kr. El ahorro se suma a lo largo del año, porque Personalizado guarda lo que apartaste cada mes',
        'Nuevo: duplica un bloque con ⧉ en modo edición. La copia conserva filas, colores y ajustes de gráfico y aparece justo después del original — pero sin importes, para que la rellenes de nuevo',
        'Nuevo: bloques listos en "Añadir bloque" — Vivienda, Comida, Transporte y Ahorro, con el tipo correcto y filas ya nombradas. Siguen el cambio de idioma como los demás nombres integrados',
        'Nuevo: una línea bajo las tarjetas que dice algo sobre el mes en vez de solo mostrar cifras — tu mayor gasto, cuánto apartaste o un déficit. Si una meta está cerca o tu ahorro ha crecido varios meses seguidos, lo dice en su lugar',
        'Nuevo: una fila puede pagarse trimestral o anualmente. Escribe el importe que pagas de verdad — 4.800 kr del seguro — y marca la fila "Anual". El presupuesto cuenta 400 kr al mes en vez de hacer que enero parezca una catástrofe. Si no tocas nada, todo sigue siendo mensual',
        'Nuevo: una línea de periodo de pago bajo el mes. Indica el día en que empieza tu periodo y la app escribe "25 dic – 24 ene" bajo cada mes. ¿Prefieres tus propias palabras para un mes? Haz clic en el texto y escribe — vacía el campo para volver a lo automático. Es solo una etiqueta: no cambia ningún importe',
        'Cambiado: "Anual" ya no divide el importe entre doce. Una suscripción anual se cobra íntegra el mes en que la pagas, así el presupuesto coincide con tu cuenta ese mes. Nueva opción: Pago único',
        'Las filas que no se repiten cada mes ya no se copian al mes siguiente — si no, febrero mostraría un cargo que nunca ocurre. Las vuelves a añadir cuando toca',
        'Corregido: copiar ya no sobrescribe un mes sin preguntar. El aviso nombra el mes y el origen, y "Todos los restantes" cuenta primero cuántos se verán afectados. Si cancelas no se escribe nada',
        'Corregido: la pestaña Ahorro ofrecía un selector de periodo, lo que hacía que una misma cuenta mostrara 12.000 kr y 1.000 kr a la vez. Un saldo es lo que tienes, no algo que se cobra',
        'Corregido: la vista anual de Personalizado cambiaba el historial al editar el diseño actual. Cada mes guarda ahora su propia estructura, así septiembre se mantiene aunque borres el bloque en octubre',
        'Corregido: la vista anual de Personalizado quedaba en una columna estrecha, un periodo que empieza el día 1 mostraba el mes anterior, y una marca de periodo dañada podía vaciar un total',
        'Corregido: "Traer del mes anterior" podía vaciar un presupuesto terminado. Un mes que solo tenía ahorro o una etiqueta de periodo contaba como presupuesto del que traer — ahora hace falta contenido real, y si no, no pasa nada',
        'Los meses de Personalizado registrados antes de que la app guardara su estructura la reciben de forma retroactiva. Sin ella, editar el diseño actual reclasificaba meses antiguos. No se toca ningún importe',
        'Eliminar una sola fila en Personalizado ahora pregunta primero, igual que un bloque entero — y el aviso cuenta también el mes en el que estás',
        'El aviso explica lo que ocurre de verdad: las filas salen del presupuesto mensual pero los importes siguen contando en la vista anual, así que las dos vistas muestran cifras distintas',
        '"Borrar importes" elimina ahora también las notas de estructura que acompañaban a esos importes, en vez de dejarlas sin nada que describir',
        'Corregido: el menú no se podía desplazar en el escritorio. Con una ventana baja, su parte inferior quedaba fuera de la pantalla, y como la cabecera está fijada, desplazar la página no servía — Importar datos y toda la zona de peligro eran inalcanzables. El menú ahora se queda dentro de la ventana y la lista se desplaza',
        'Corregido: una fila que no es mensual indicaba su periodo dos veces — "Pago único" en el selector y "pago único" al lado — y el selector aparecía cortado a media palabra. El periodo se indica ahora en un solo lugar, y la palabra cabe entera',
        'Corregido: con la app abierta en dos pestañas, una podía sobrescribir en silencio los cambios de la otra. Si subías el sueldo en una y cambiabas el alquiler en la otra, solo quedaba el alquiler, sin aviso alguno. Las pestañas ahora se mantienen al día entre sí, así que ambos cambios se conservan',
        'Corregido: en el diseño personalizado el menú ofrecía Copiar presupuesto y Restablecer mes — pero actuaban sobre el presupuesto clásico, datos que no estabas viendo, e informaban de éxito igualmente. Ahora solo aparecen en Clásico y Combinado, donde corresponden',
        'Corregido: un idioma o una moneda dañados dejaban la app completamente en blanco al arrancar, sin menú para volver atrás. Ahora se comprueban ambos, al iniciar y al importar — un archivo con un idioma desconocido se rechaza en vez de reemplazar antes tu presupuesto',
        'Nuevo: si el navegador se niega a guardar — almacenamiento lleno o desactivado — la app lo dice claramente en vez de dejar que el cambio parezca guardado. El cambio sigue en pantalla, y desde ahí puedes reintentar o exportar tus datos',
        'Corregido: en Distribución de gastos el porcentaje se medía sobre los ingresos mientras el círculo se dibujaba sobre los gastos. Un único gasto llenaba todo el círculo y aun así ponía 45 %. Ahora ambos son proporción de los gastos',
        'Corregido: en móvil los importes de las tarjetas de resumen se cortaban — 30 000,50 kr quedaba en 30 000,5… Las tarjetas van ahora de dos en dos con Resto debajo, así que los importes normales con decimales se ven enteros incluso en una pantalla de 320 px',
        'Corregido: el gráfico anual comparaba tipos de cifra distintos. Ingresos y gastos son flujos, el ahorro es un saldo — pero los tres se dibujaban como barras iguales, así que un fondo de 48 000 kr era la barra más alta del año cada mes y aplastaba las cifras que dan nombre al gráfico. El saldo es ahora una línea con su propio eje a la derecha',
        'Corregido: un mes que nunca rellenaste aparecía como 0 kr en la vista anual — un mes sin ingresos ni gastos. Ahora muestra –, igual que ya hacía la columna de ahorro. Un mes que creaste y dejaste a cero sigue contando como un cero real',
        'Corregido: Progreso de metas mostraba 0 % antes de que hubieras creado ninguna meta — una puntuación de un juego que no habías empezado. Ahora muestra – con una explicación, como las tarjetas de al lado',
        'Cambiado: entre 640 y 900 px las tarjetas de resumen se apilaban una por fila, así que una ventana a media anchura gastaba más altura en tres cifras que un móvil. Ahora van tres en fila y los gráficos se ven sin desplazarse',
      ],
    },
  },
  {
    version: '1.10.6',
    date: '2026-07-31',
    title: { sv: 'Målbeloppet också', en: 'The target field too', es: 'También el importe objetivo' },
    items: {
      sv: [
        'Rättat: blockets målbelopp i Anpassad layout hade samma fel som beloppsfälten — "1e309" blev tyst målet 1 309 kr, och några hundra siffror gjorde att målet försvann helt',
        'Målbeloppet visar nu samma tydliga fel som övriga belopp, och ditt tidigare mål står kvar',
      ],
      en: [
        'Fixed: the block target field in Custom layout had the same bug as the amount fields — "1e309" quietly became a target of 1,309 kr, and a few hundred digits made the target disappear entirely',
        'The target field now shows the same clear error as every other amount, and your previous target stands',
      ],
      es: [
        'Corregido: el importe objetivo del bloque en el diseño personalizado tenía el mismo fallo que los importes — "1e309" se convertía silenciosamente en un objetivo de 1.309 kr, y unos cientos de dígitos hacían desaparecer el objetivo',
        'El importe objetivo muestra ahora el mismo error claro que los demás importes, y tu objetivo anterior se mantiene',
      ],
    },
  },
  {
    version: '1.10.5',
    date: '2026-07-30',
    title: { sv: 'Inga tysta ändringar', en: 'No silent changes', es: 'Sin cambios silenciosos' },
    items: {
      sv: [
        'Rättat: i Anpassad layout kunde "1e309" tyst bli 1 309 kr och sparas — appen ändrar aldrig ditt belopp längre, den säger ifrån',
        'Ogiltiga belopp i Anpassad layout visar nu samma tydliga fel som Budget, och din summa ligger kvar',
        'Rättat: säkerhetskopior godkände Custom-belopp som appen sedan nollställde vid inläsning — de avvisas nu direkt',
        'Rättat: sektionsrubriken hamnade delvis bakom snabbnavigeringen på smala mobiler',
        'Sparmål: felmeddelandet beskriver nu vad som faktiskt är fel — tomt, noll eller ogiltigt belopp',
      ],
      en: [
        'Fixed: in Custom layout "1e309" could quietly become 1,309 kr and be saved — the app never rewrites your amount now, it tells you',
        'Invalid amounts in Custom layout show the same clear error as Budget, and your total stays put',
        'Fixed: backups accepted Custom amounts the app then reset to 0 on load — they are now rejected up front',
        'Fixed: the section heading sat partly behind the quick-nav on narrow phones',
        'Savings goals: the error now describes the actual problem — blank, zero, or an invalid amount',
      ],
      es: [
        'Corregido: en el diseño personalizado "1e309" podía convertirse silenciosamente en 1.309 kr y guardarse — la app ya nunca reescribe tu importe, te avisa',
        'Los importes no válidos en el diseño personalizado muestran el mismo error claro que Presupuesto, y tu total se mantiene',
        'Corregido: las copias aceptaban importes personalizados que la app luego ponía a 0 al cargar — ahora se rechazan de entrada',
        'Corregido: el título de sección quedaba parcialmente detrás de la navegación rápida en móviles estrechos',
        'Metas de ahorro: el error ahora describe el problema real — vacío, cero o importe no válido',
      ],
    },
  },
  {
    version: '1.10.4',
    date: '2026-07-26',
    title: { sv: 'Säkrare belopp', en: 'Safer amounts', es: 'Importes más seguros' },
    items: {
      sv: [
        'Rättat: extrema tal (som 1e309 eller 400 siffror) visades som "infinity kr" och blev tyst 0 kr efter omladdning — nu avvisas de med ett tydligt fel och ditt tidigare belopp står kvar',
        'Samma beloppsregler gäller nu överallt: budget, sparmål, egen layout och import av säkerhetskopia',
        'Belopp som redan blivit trasiga i lagringen läses nu som 0 istället för att förstöra hela summan',
        'Underskott syns tydligt: eget färgläge och texten "Underskott: X kr" — inte bara en röd siffra på grön bakgrund',
        'Bättre kontrast i sammanfattningskorten (klarar WCAG AA i alla paletter och båda temana)',
        'Säkerhetskopior kontrollerar nu hela sparmålet — namn, datum och färg, inte bara beloppen',
        'Snabbnavigeringen i Kombinerad layout visar hela ordet även på de smalaste mobilerna',
        'Accentfärgerna har riktiga namn och berättar för skärmläsare vilken som är vald',
        '"Kvar att leva på" räknas nu på hela månaden och står stilla — förut växte siffran ju närmare månadsskiftet man kom',
        'Beloppen i budgetraderna är mörkare och lättare att läsa, och står nu i en rak kolumn även när raden har en ta bort-knapp',
      ],
      en: [
        'Fixed: extreme numbers (like 1e309 or 400 digits) showed as "infinity kr" and silently became 0 kr after a reload — they are now rejected with a clear error and your previous amount stands',
        'The same amount rules now apply everywhere: budget, savings goals, custom layout and backup import',
        'Amounts already corrupted in storage now read as 0 instead of poisoning the whole total',
        'Overspending is unmistakable: its own colour state and the words "Overspend: X" — not just a red number on a green card',
        'Better contrast in the summary cards (WCAG AA in every palette and both themes)',
        'Backups now validate the whole savings goal — name, deadline and colour, not just the amounts',
        'The Combined quick-nav shows the full word even on the narrowest phones',
        'Accent colours have real names and tell screen readers which one is selected',
        '"Left to live on" is now based on the whole month and stays put — the figure used to climb as the month ran out',
        'Row amounts are darker and easier to read, and now line up in a straight column even when a row has a delete button',
      ],
      es: [
        'Corregido: los números extremos (como 1e309 o 400 dígitos) se mostraban como "infinity kr" y pasaban silenciosamente a 0 kr tras recargar — ahora se rechazan con un error claro y tu importe anterior se mantiene',
        'Las mismas reglas de importe se aplican en todas partes: presupuesto, metas, diseño personalizado e importación de copias',
        'Los importes ya dañados en el almacenamiento se leen como 0 en vez de estropear todo el total',
        'El déficit se ve claramente: su propio estado de color y el texto "Déficit: X" — no solo un número rojo sobre fondo verde',
        'Mejor contraste en las tarjetas de resumen (WCAG AA en todas las paletas y ambos temas)',
        'Las copias de seguridad validan la meta completa — nombre, fecha y color, no solo los importes',
        'La navegación rápida del diseño combinado muestra la palabra completa incluso en los móviles más estrechos',
        'Los colores de acento tienen nombres reales e indican a los lectores de pantalla cuál está seleccionado',
        '"Para vivir este mes" se calcula sobre el mes completo y ya no cambia — antes la cifra subía a medida que acababa el mes',
        'Los importes de las filas son más oscuros y legibles, y ahora se alinean en columna aunque la fila tenga botón de eliminar',
      ],
    },
  },
  {
    version: '1.10.3',
    date: '2026-07-25',
    title: { sv: 'Sparmål i budgeten', en: 'Goals in the budget', es: 'Metas en el presupuesto' },
    items: {
      sv: [
        'Rättat: sparmålens rader dök upp i månader som redan passerat — avslutade månader lämnas nu orörda',
        'Rättat: att bara bläddra till en månad skriver inte längre om den; raden erbjuds men sparas först när du fyller i något',
        'Rättat: en borttagen målrad kom tillbaka med 0 kr och åt upp beloppet som stod där — nu stannar den borta och målet behåller det du sparat',
        'Städar automatiskt bort de spökrader som den gamla versionen redan hunnit spara i passerade månader — rader med pengar i behålls',
      ],
      en: [
        'Fixed: savings-goal rows appeared in months that had already ended — finished months are now left untouched',
        'Fixed: merely browsing to a month no longer rewrites it; the row is offered but only saved once you enter something',
        'Fixed: a deleted goal row came back at 0 kr and swallowed the amount that was in it — it now stays gone and the goal keeps what you saved',
        'Automatically clears the leftover rows the old version had already saved into finished months — rows with money in them are kept',
      ],
      es: [
        'Corregido: las filas de metas aparecían en meses ya terminados — los meses cerrados ahora quedan intactos',
        'Corregido: con solo abrir un mes ya no se reescribe; la fila se ofrece pero solo se guarda cuando introduces algo',
        'Corregido: una fila de meta eliminada volvía con 0 kr y se comía el importe que había — ahora no vuelve y la meta conserva lo ahorrado',
        'Limpia automáticamente las filas que la versión anterior ya había guardado en meses cerrados — las filas con dinero se conservan',
      ],
    },
  },
  {
    version: '1.10.1',
    date: '2026-07-19',
    title: { sv: 'Trygghetsfixar', en: 'Trust fixes', es: 'Correcciones de confianza' },
    items: {
      sv: [
        'Rättat: sparmallen kunde visa ett stort uttag du aldrig gjort — att skapa kategorier räknas inte längre som ett registrerat saldo',
        'Rättat: snabbnavigeringen i Kombinerad layout täckte månadsväljaren och menyn på mobil',
        'Rättat: en dold skärmläsartabell kunde göra hela sidan sidledes-scrollbar på mobil',
        'År-fliken visar nu tydligt att helårsraden är "Sparat under året" och berättar vilken decembermånad som saknas',
        'Ett skrivfel i sparplanen nollställer inte längre prognosen — grafen behåller senaste giltiga värde',
        'Säkerhetskopior kontrolleras nu med exakt samma regler som appen — en godkänd import kan inte tappa sparplanen',
        'Custom-dialoger har nu riktiga namn för skärmläsare',
        'Extremt stora kategorisummor trycker inte längre bort kategorinamnet',
      ],
      en: [
        'Fixed: the savings template could show a large withdrawal you never made — creating categories no longer counts as a recorded balance',
        'Fixed: the quick-nav in Combined layout covered the month selector and menu on mobile',
        'Fixed: a hidden screen-reader table could make the whole page scroll sideways on mobile',
        'The Year tab now clearly labels the full-year row as "Saved during the year" and tells you which December is missing',
        'A typo in the savings plan no longer zeroes the projection — the chart keeps the last valid value',
        'Backups are now checked with exactly the app\'s own rules — an approved import can\'t silently lose the savings plan',
        'Custom dialogs now have real names for screen readers',
        'Extremely large category totals no longer push out the category name',
      ],
      es: [
        'Corregido: la plantilla de ahorro podía mostrar una gran retirada que nunca hiciste — crear categorías ya no cuenta como saldo registrado',
        'Corregido: la navegación rápida del diseño combinado tapaba el selector de mes y el menú en móvil',
        'Corregido: una tabla oculta para lectores de pantalla podía hacer que toda la página se desplazara lateralmente',
        'La pestaña Año ahora etiqueta claramente la fila anual como "Ahorrado durante el año" e indica qué diciembre falta',
        'Un error al escribir en el plan de ahorro ya no pone la proyección a cero — el gráfico mantiene el último valor válido',
        'Las copias de seguridad se validan con las mismas reglas de la app — una importación aprobada no puede perder el plan',
        'Los diálogos de Custom ahora tienen nombres reales para lectores de pantalla',
        'Los importes de categoría extremadamente grandes ya no ocultan el nombre de la categoría',
      ],
    },
  },
  {
    version: '1.10.0',
    date: '2026-07-16',
    title: { sv: 'Sparplan', en: 'Savings plan', es: 'Plan de ahorro' },
    items: {
      sv: [
        'Ny sparplan i Plan-fliken: ange månadssparande och förväntad avkastning',
        'Se din prognos 5 år framåt — med ränta på ränta',
        '"Plan mot verklighet": ligger du före eller efter din plan?',
        '"Kvar att leva på": det som är kvar utslaget per dag och per vecka',
        'Tydligare sparande: "Totalt sparat" visar hela ditt sparkapital, och "Sparat denna månad" visar hur mycket det växte',
        'Rättat: sparkvot, årssumma och plan-jämförelsen la ihop ditt sparkapital flera gånger',
        'Rättat: en månad du inte fyllt i visade ett stort uttag — nu står det "–" tills du registrerat saldot',
        'Rättat: ett sparsaldo på 0 räknas nu som en riktig nolla i Sparande, Plan och År',
        'Rättat: sparkurvan dyker inte längre till noll för månader utan uppgifter',
        'År-fliken skiljer nu på "Sparsaldo" (per månad) och "Sparat under året" (totalen)',
        'Import av säkerhetskopia ersätter nu all data på riktigt — gamla månader blir inte kvar',
        'Import kontrollerar hela filen först och ångrar allt om något går fel',
        'Custom-blockens standardnamn följer nu med när du byter språk — dina egna namn rörs aldrig',
        'Sparplanen stoppar orimliga tal med tydliga fel, och kan nu raderas',
        'Snabbare start: appen laddar diagramkoden först när den behövs (60 % mindre)',
        'Kombinerad layout på mobil: fast snabbnavigering mellan sektionerna',
        'Fungerar bättre på smala skärmar och med mycket stora belopp (10 md kr)',
        'Bättre kontrast i diagram, dolda datatabeller för skärmläsare och låst bakgrund bakom dialoger',
      ],
      en: [
        'New savings plan in the Plan tab: set monthly saving and expected return',
        'See your 5-year projection — with compound growth',
        '"Plan vs reality": are you ahead of or behind your plan?',
        '"Left to live on": your remaining money split per day and per week',
        'Clearer savings: "Total saved" shows your whole pot, and "Saved this month" shows how much it grew',
        'Fixed: savings rate, the yearly total and the plan comparison were adding your savings pot up more than once',
        'Fixed: a month you had not filled in showed a large withdrawal — it now reads "–" until you record the balance',
        'Fixed: a savings balance of 0 now counts as a real zero in Savings, Plan and Year',
        'Fixed: the savings curve no longer dives to zero for months with no data',
        'The Year tab now separates "Savings balance" (per month) from "Saved during the year" (the total)',
        'Importing a backup now truly replaces all data — old months no longer linger',
        'Import checks the whole file first and undoes everything if anything goes wrong',
        'Custom blocks\' default names now follow your language switch — your own names are never touched',
        'The savings plan rejects impossible numbers with clear errors, and can now be deleted',
        'Faster start: chart code loads only when needed (60% smaller)',
        'Combined layout on mobile: a sticky quick-nav between sections',
        'Works better on narrow screens and with very large amounts ($10B)',
        'Better chart contrast, hidden data tables for screen readers, and a locked background behind dialogs',
      ],
      es: [
        'Nuevo plan de ahorro en Plan: define ahorro mensual y rendimiento esperado',
        'Mira tu proyección a 5 años — con interés compuesto',
        '"Plan frente a realidad": ¿vas por delante o por detrás de tu plan?',
        '"Para vivir este mes": lo que te queda repartido por día y por semana',
        'Ahorro más claro: "Ahorro total" muestra todo tu capital y "Ahorrado este mes" cuánto creció',
        'Corregido: la tasa de ahorro, el total anual y la comparación con el plan sumaban tu ahorro varias veces',
        'Corregido: un mes sin rellenar mostraba una gran retirada — ahora pone "–" hasta que registres el saldo',
        'Corregido: un saldo de ahorro de 0 ahora cuenta como un cero real en Ahorro, Plan y Año',
        'Corregido: la curva de ahorro ya no cae a cero en los meses sin datos',
        'La pestaña Año ahora distingue "Saldo de ahorro" (por mes) de "Ahorrado durante el año" (el total)',
        'Importar una copia ahora reemplaza de verdad todos los datos: los meses antiguos ya no permanecen',
        'La importación valida todo el archivo primero y lo deshace todo si algo falla',
        'Los nombres predeterminados de los bloques Custom siguen tu idioma — tus propios nombres nunca se tocan',
        'El plan de ahorro rechaza números imposibles con errores claros, y ahora se puede eliminar',
        'Inicio más rápido: el código de los gráficos se carga solo cuando hace falta (60 % menos)',
        'Diseño combinado en móvil: navegación rápida fija entre secciones',
        'Funciona mejor en pantallas estrechas y con importes muy grandes',
        'Mejor contraste en gráficos, tablas de datos ocultas para lectores de pantalla y fondo bloqueado tras los diálogos',
      ],
    },
  },
  {
    version: '1.9.1',
    date: '2026-07-12',
    title: { sv: 'Finslipning', en: 'Polish', es: 'Pulido' },
    items: {
      sv: [
        'Fungerar nu även på mycket smala mobilskärmar',
        'Ören visas alltid med två decimaler (1 200,50 kr)',
        'Sparmål kräver ett målbelopp över 0 — med tydligt felmeddelande',
      ],
      en: [
        'Now works on very narrow phone screens too',
        'Cents always show two decimals (1,200.50)',
        'Savings goals require a target above 0 — with a clear error message',
      ],
      es: [
        'Ahora funciona también en pantallas muy estrechas',
        'Los céntimos siempre muestran dos decimales (1.200,50 €)',
        'Las metas requieren un importe mayor que 0 — con un mensaje de error claro',
      ],
    },
  },
  {
    version: '1.9.0',
    date: '2026-07-09',
    title: { sv: 'Kvalitetslyft', en: 'Quality update', es: 'Mejoras de calidad' },
    items: {
      sv: [
        'Ny välkomstskärm för nya användare',
        'Tydligare siffror för sparande och sparkvot',
        'Säkrare månadsåterställning – sparmål tappas inte längre',
        'Smidigare på mobilen: snabbare inmatning och stabil meny',
        'Lättare att läsa diagram och bättre kontrast',
        'Nytt formulär för sparmål med Spara/Avbryt',
        'Belopp kan nu visas med ören',
      ],
      en: [
        'New welcome screen for first-time users',
        'Clearer savings and savings-rate numbers',
        'Safer month reset – goals are no longer lost',
        'Smoother on mobile: faster entry and a steadier menu',
        'Easier-to-read charts and better contrast',
        'New savings-goal form with Save/Cancel',
        'Amounts can now show decimals',
      ],
      es: [
        'Nueva pantalla de bienvenida',
        'Cifras de ahorro y tasa de ahorro más claras',
        'Reinicio de mes más seguro: ya no se pierden las metas',
        'Más fluido en móvil: entrada rápida y menú estable',
        'Gráficos más legibles y mejor contraste',
        'Nuevo formulario de metas con Guardar/Cancelar',
        'Los importes pueden mostrar decimales',
      ],
    },
  },
  {
    version: '1.8.1',
    date: '2026-07-03',
    title: { sv: 'Decimalfix', en: 'Decimal fix', es: 'Corrección de decimales' },
    items: {
      sv: ['Custom-läget hanterar nu decimaltecken korrekt (t.ex. 970,5)'],
      en: ['Custom mode now handles decimal separators correctly (e.g. 970.5)'],
      es: ['El modo personalizado ahora maneja bien los separadores decimales (p. ej. 970,5)'],
    },
  },
  {
    version: '1.8.0',
    date: '2026-07-02',
    title: { sv: 'Tillgänglighet', en: 'Accessibility', es: 'Accesibilidad' },
    items: {
      sv: [
        'Introduktionsguider för tomma vyer',
        'Tydligare flik- och knappnamn för skärmläsare',
        'Fler mobilförbättringar',
        'Enhetligare design',
      ],
      en: [
        'Onboarding guides for empty views',
        'Clearer tab & button names for screen readers',
        'More mobile refinements',
        'A more consistent design',
      ],
      es: [
        'Guías de introducción para vistas vacías',
        'Nombres de pestañas y botones más claros para lectores de pantalla',
        'Más mejoras en móvil',
        'Un diseño más consistente',
      ],
    },
  },
  {
    version: '1.7.0',
    date: '2026-06-30',
    title: { sv: 'Spanska, valutor & teman', en: 'Spanish, currencies & themes', es: 'Español, monedas y temas' },
    items: {
      sv: [
        'Spanska tillagt (svenska/engelska/spanska)',
        'Byt valuta: kr, €, $, £',
        'Temabyggare med paletter och mörkt/ljust läge',
        'Nya layouter: kombinerad och egen (Custom)',
      ],
      en: [
        'Spanish added (Swedish/English/Spanish)',
        'Switch currency: kr, €, $, £',
        'Theme builder with palettes and dark/light mode',
        'New layouts: combined and custom',
      ],
      es: [
        'Español añadido (sueco/inglés/español)',
        'Cambia de moneda: kr, €, $, £',
        'Creador de temas con paletas y modo claro/oscuro',
        'Nuevos diseños: combinado y personalizado',
      ],
    },
  },
  {
    version: '1.6.0',
    date: '2026-06-24',
    title: { sv: 'Pension & år', en: 'Pension & year', es: 'Pensión y año' },
    items: {
      sv: [
        'Pension redovisas som en egen långsiktig hink',
        'Sparande visas nu i årsöversikten',
      ],
      en: [
        'Pension is shown as its own long-term bucket',
        'Savings now appear in the yearly overview',
      ],
      es: [
        'La pensión se muestra como su propia partida a largo plazo',
        'El ahorro ahora aparece en el resumen anual',
      ],
    },
  },
  {
    version: '1.5.0',
    date: '2026-06-23',
    title: { sv: 'Plan & Översikt', en: 'Plan & Overview', es: 'Plan y resumen' },
    items: {
      sv: [
        'Ny flik: Plan & Översikt med sparmål',
        'Byt diagramtyp',
        'Nytt typsnitt',
        'Återställ månad-funktion',
      ],
      en: [
        'New tab: Plan & Overview with savings goals',
        'Switch chart type',
        'New typeface',
        'Reset-month option',
      ],
      es: [
        'Nueva pestaña: Plan y resumen con metas de ahorro',
        'Cambia el tipo de gráfico',
        'Nueva tipografía',
        'Opción de reiniciar el mes',
      ],
    },
  },
  {
    version: '1.4.0',
    date: '2026-06-20',
    title: { sv: 'Ny design (Sorbet)', en: 'New look (Sorbet)', es: 'Nuevo aspecto (Sorbet)' },
    items: {
      sv: [
        'Helt ny visuell design (Sorbet)',
        'Omgjord navigation',
        'Hantera sparkategorier',
        'Mobilpolering',
      ],
      en: [
        'Brand-new visual design (Sorbet)',
        'Reworked navigation',
        'Manage savings categories',
        'Mobile polish',
      ],
      es: [
        'Diseño visual completamente nuevo (Sorbet)',
        'Navegación renovada',
        'Gestiona categorías de ahorro',
        'Mejoras en móvil',
      ],
    },
  },
  {
    version: '1.3.0',
    date: '2026-06-19',
    title: { sv: 'Egna kategorier', en: 'Custom categories', es: 'Categorías propias' },
    items: {
      sv: ['Skapa egna budgetkategorier', 'Påminnelse om säkerhetskopiering'],
      en: ['Create your own budget categories', 'Backup reminder'],
      es: ['Crea tus propias categorías de presupuesto', 'Recordatorio de copia de seguridad'],
    },
  },
  {
    version: '1.2.0',
    date: '2026-06-16',
    title: { sv: 'Säkerhetskopior & översikt', en: 'Backups & overview', es: 'Copias y resumen' },
    items: {
      sv: ['Exportera och importera all data', 'Sparkvot', 'Årsöversikt'],
      en: ['Export and import all your data', 'Savings rate', 'Annual overview'],
      es: ['Exporta e importa todos tus datos', 'Tasa de ahorro', 'Resumen anual'],
    },
  },
  {
    version: '1.1.0',
    date: '2026-06-15',
    title: { sv: 'Två språk', en: 'Two languages', es: 'Dos idiomas' },
    items: {
      sv: [
        'Växla mellan svenska och engelska',
        'Inbyggda etiketter översätts automatiskt',
        'Mobil- och buggfixar',
      ],
      en: [
        'Switch between Swedish and English',
        'Built-in labels translate automatically',
        'Mobile & bug fixes',
      ],
      es: [
        'Cambia entre sueco e inglés',
        'Las etiquetas integradas se traducen automáticamente',
        'Correcciones de móvil y de errores',
      ],
    },
  },
  {
    version: '1.0.0',
    date: '2026-06-13',
    title: { sv: 'Lansering', en: 'Launch', es: 'Lanzamiento' },
    items: {
      sv: [
        'Månadsbudget med inkomster, utgifter och sparande',
        'Fungerar offline som app (PWA)',
        'All data lagras lokalt på din enhet',
      ],
      en: [
        'Monthly budget with income, expenses and savings',
        'Works offline as an app (PWA)',
        'All data stored locally on your device',
      ],
      es: [
        'Presupuesto mensual con ingresos, gastos y ahorro',
        'Funciona sin conexión como app (PWA)',
        'Todos los datos se guardan localmente en tu dispositivo',
      ],
    },
  },
];

/** The current app version — compared against budget_changelog_seen to decide
 *  whether to show the "new update" badge. */
export const LATEST_VERSION = CHANGELOG[0].version;
